FROM openjdk:21-jdk-slim
WORKDIR /app

COPY wait-for-it.sh /wait-for-it.sh
COPY target/client-0.0.1-SNAPSHOT.jar app.jar

RUN chmod +x /wait-for-it.sh

ENTRYPOINT ["/wait-for-it.sh", "status-service:8081", "--", "java", "-jar", "app.jar"]
