---
services:
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-net

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - status-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - spring-cloud-net

  status-service:
    build:
      context: ./status-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - spring-cloud-net
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - spring-cloud-net

networks:
  spring-cloud-net:
    driver: bridge
