---
services:
  eureka-server:
    build:
      context: ./eureka-server
    environment:
      - "EUREKA_SERVER_NAME=eureka-server"
    ports:
      - "8761:8761"
    networks:
      - status-server-network

  status-service-1:
    build:
      context: ./status-service
    environment:
      - "SERVER_PORT=9001"
      - "STATUS_SERVICE_NAME=status-service"
      - "STATUS_SERVICE_NUMBER=1"
      - "EUREKA_SERVER_NAME=eureka-server"
    ports:
      - "9001:9001"
    networks:
      - status-server-network
  status-service-2:
    build:
      context: ./status-service
    environment:
      - "SERVER_PORT=9002"
      - "STATUS_SERVICE_NAME=status-service"
      - "STATUS_SERVICE_NUMBER=2"
      - "EUREKA_SERVER_NAME=eureka-server"
    ports:
      - "9002:9002"
    networks:
      - status-server-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - status-server-network

networks:
  status-server-network:
    driver: bridge
