services:
  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-server
    environment:
      - EUREKA_SERVER_NAME=eureka-server
    ports:
      - "8761:8761"
    networks:
      - status-server-network

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    depends_on:
      - eureka-server
    environment:
      - API_GATEWAY_NAME=api-gateway
      - EUREKA_SERVER_NAME=eureka-server
    ports:
      - "9000:9000"
    networks:
      - status-server-network

  status-service-1:
    image: status-service:latest
    build:
      context: ./status-service
    depends_on:
      - eureka-server
    environment:
      - SERVER_PORT=9001
      - STATUS_SERVICE_NAME=status-service
      - EUREKA_SERVER_NAME=eureka-server
    ports:
      - "9001:9001"
    networks:
      - status-server-network

  status-service-2:
    image: status-service:latest
    build:
      context: ./status-service
    depends_on:
      - eureka-server
    environment:
      - SERVER_PORT=9002
      - STATUS_SERVICE_NAME=status-service
      - EUREKA_SERVER_NAME=eureka-server
    ports:
      - "9002:9002"
    networks:
      - status-server-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    networks:
      - status-server-network
    depends_on:
      - api-gateway

networks:
  status-server-network:
    driver: bridge