server:
    port: 8080

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
              - id: client
                uri: lb://CLIENT
                predicates:
                    - Path=/client/**
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
logging:
    level:
        org.springframework.cloud.gateway: DEBUG
        org.springframework.web: DEBUG
