spring:
  application:
    name: status-service
server:
  port: ${SERVER_PORT:9001}
eureka:
  instance:
    hostname: ${STATUS_SERVICE_NAME:localhost}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_NAME:localhost}:8761/eureka
status:
  peers:
    - http://${STATUS_SERVICE_NAME:localhost}:9001
    - http://${STATUS_SERVICE_NAME:localhost}:9002