spring:
  application:
    name: status-service
server:
  port: 9001

eureka:
  instance:
    hostname: status-service
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka