spring:
  application:
    name: ${STATUS_SERVICE_NAME:localhost}
server:
  port: ${SERVER_PORT:9001}
eureka:
  instance:
    hostname: ${STATUS_SERVICE_NAME:localhost}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_NAME:localhost}:8761/eureka
status:
  peers:
    - http://${STATUS_SERVICE_NAME:localhost}-1:9001
    - http://${STATUS_SERVICE_NAME:localhost}-2:9002
