FROM openjdk:21-jdk-slim
WORKDIR /app

COPY wait-for-it.sh /wait-for-it.sh
COPY target/status-service-0.0.1-SNAPSHOT.jar app.jar

RUN chmod +x /wait-for-it.sh

ENTRYPOINT ["/wait-for-it.sh", "eureka-server:8761", "--", "java", "-jar", "app.jar"]