spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
