spring:
  application:
    name: ${EUREKA_SERVER_NAME:localhost}
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_NAME:localhost}:8761/eureka
    register-with-eureka: false
    fetch-registry: false
  eureka:
  server:
    enableSelfPreservation: true
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  max-age: 3600
