spring:
    application:
        name: client
    profiles:
        active: default
    eureka:
        client:
            serviceUrl:
                defaultZone: http://localhost:8761/eureka/
            registerWithEureka: true
            fetchRegistry: true
        instance:
            instance-id: ${spring.application.name}:${server.port}:${random.value}
            metadata-map:
                port: ${server.port}
            prefer-ip-address: true
server:
    port: 0

logging:
    level:
        org.springframework.cloud.config: DEBUG
        org.springframework.boot.context.config: DEBUG
