spring:
  application:
    name: client
  profiles:
    active: default
eureka:
  instance:
    instance-id: ${spring.application.name}-id-${random.int(100000,999999)}
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
server:
  port: 0

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.context.config: DEBUG
